<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ78lSHY\FunctionalTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ78lSHY/FunctionalTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ78lSHY.legacy');

    return;
}

if (!\class_exists(FunctionalTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ78lSHY\FunctionalTestDebugProjectContainer::class, FunctionalTestDebugProjectContainer::class, false);
}

return new \ContainerZ78lSHY\FunctionalTestDebugProjectContainer(array(
    'container.build_hash' => 'Z78lSHY',
    'container.build_id' => '1a0c2aa3',
    'container.build_time' => 1535362314,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ78lSHY');
