<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy' shared service.

return $this->services['SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy'] = new \SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy();
