<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplytestable_pagecache.cache_validator_headers_service' shared service.

return $this->services['simplytestable_pagecache.cache_validator_headers_service'] = new \SimplyTestable\PageCacheBundle\Services\CacheValidatorHeadersService(($this->services['SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy'] ?? $this->services['SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy'] = new \SimplyTestable\PageCacheBundle\Tests\Functional\EntityManagerProxy()));
