<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplytestable_pagecache.command.cache_validator.clear' shared service.

return $this->services['simplytestable_pagecache.command.cache_validator.clear'] = new \SimplyTestable\PageCacheBundle\Command\ClearCommand(($this->services['simplytestable_pagecache.cache_validator_headers_service'] ?? $this->load('getSimplytestablePagecache_CacheValidatorHeadersServiceService.php')));
