<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simplytestable_pagecache.cacheable_response_factory' shared service.

return $this->services['simplytestable_pagecache.cacheable_response_factory'] = new \SimplyTestable\PageCacheBundle\Services\CacheableResponseFactory(($this->services['simplytestable_pagecache.cache_validator_headers_service'] ?? $this->load('getSimplytestablePagecache_CacheValidatorHeadersServiceService.php')), ($this->services['simplytestable_pagecache.cache_validator_identifier.parameters_factory'] ?? $this->services['simplytestable_pagecache.cache_validator_identifier.parameters_factory'] = new \SimplyTestable\PageCacheBundle\Services\CacheValidatorIdentifier\ParametersFactory()));
